### ISSUE TITLE
Static pages can not be found (404)

### ISSUE THREAD

**Issue by DavidEibl** [serlo-org/athene2#628] opened 2017-11-21 20:58 UTC
Opening about page (either for top and bottom navigation) causes a 404 error message being displayed instead of opening page.
https://de.serlo.org/serlo

**Comment by Knorrke** [comment] 2017-11-22 07:32
Thanks @DavidEibl for opening this issue. This happens sometimes lately, its not yet clear why... the page is accessible a few minutes later, so hard to reproduce. Can you remember what you did before trying to access the page? And was it immediately before you wrote the issue? Then i can look into our event history

**Comment by DavidEibl** [comment] 2017-11-22 09:59
Happend over a total period of around 1 hour up to the point where I published the issue.
Occured immediately after opening main page and later as well after opening other static pages.
OS: macOS Sierra 10.12.3
Browser: Firefox Quantum (57.0)
ISP: Vodafone (If this helps filtering logs ;-) )

**Comment by Knorrke** [comment] 2017-11-22 20:13
Thanks for the information. Sadly as far as I can tell there weren't any activities on the platform, that could have caused this, so we'll have to further check why this happens.

ping @arekkas I checked our event history, there were no events logged in the time of this issue. The last thing was 7 hours earlier a new edit for https://de.serlo.org/presse Do you think the problem could be delayed that long (i.e. something with cache or reindexing, etc.?) or do you have a different idea what could be causing this, if its not taxonomy or page changes? The only change on software side that (in my understanding) could maybe cause this is https://github.com/serlo-org/athene2/pull/602, or are there more things to consider?

**Comment by SimonKoehl** [comment] 2018-06-27 11:57
@arekkas Phillip found a hint: The bug seems to be connected with the language versions. It only occurs on pages which share a URL like /serlo or /community on different language tenants. And it looks like, as if the page ony works on one of the tenants at the same time

**Comment by Knorrke** [comment] 2018-07-02 09:23
@SimonKoehl That was the key information, thanks! Is fixed in my PR :-)

**Comment by SimonKoehl** [comment] 2018-07-02 10:02
Nice! I forwarded the "thanks" to Phillip

**Closed** 2018-07-02 15:37 UTC
