### ISSUE TITLE
Footer in english

### ISSUE THREAD

**Issue by amankumar1419** [serlo-org/athene2#717] opened 2018-07-19 16:12 UTC
Shouldn't the footer be in Hindi too?
General
Subjects
stay in touch
legal terms

**Comment by amankumar1419** [comment] 2018-07-19 16:14
Also the pages and taxonomy doesn't work in the backend for Hindi tenant

**Comment by inyono** [comment] 2018-07-27 03:18
Duplicate of #665. Seems like the preparations for https://hi.serlo.org aren't completely done, yet

**Closed by inyono** 2018-07-27 03:18 UTC
