### ISSUE TITLE
Image doesn‘t load on mobile

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#804] opened 2018-11-15 17:20 UTC
https://de.serlo.org/mathe/geometrie/satzgruppe-pythagoras/ueberblick-satz-pythagoras-hypotenuse-die-katheten

iPhone SE, Safari

**Comment by Knorrke** [comment] 2018-11-16 00:54
duplicate of #748

**Closed by Knorrke** 2018-11-16 00:54 UTC
