### ISSUE TITLE
editor doesn't work on iPad

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#151] opened 2015-07-17 07:44 UTC
I tried to edit a page. The editor opens but only the title loads and the rest of the editor remains empty.

**Comment by SimonKoehl** [comment] 2015-07-17 07:44
browser: Safari

**Comment by inyono** [comment] 2015-07-17 09:14
@arekkas 

> I don't think it's going to be possible to get the current editor working for mobile and even if, the UX is probably going to be not so good.

> With a new editor - where we're going to focus on mobile UX as well - on the horizon, I'd say to postpone this and maybe add a warning or disable editing on mobile all together

**Comment by arekkas** [comment] 2015-07-17 09:25
oh sorry i mixed up the issues, wanted to assign you to the menu one...

**Comment by inyono** [comment] 2015-07-17 09:26
This works on my iPad, too, btw

**Comment by arekkas** [comment] 2015-07-17 09:26
Maybe older IPads have problems, did you try the iOS simluator?

**Comment by inyono** [comment] 2015-07-17 09:27
not yet, let me try

**Comment by inyono** [comment] 2015-07-17 09:50
Both the editor and the navigation work on iPad 2, iOS 7.1 in the iOS simulator (Thats the oldest device and iOS version my XCode can simulate)

**Comment by arekkas** [comment] 2015-07-22 18:20
I'm closing this due to being unable to reproduce this and the fact, that the editor is probably not going to be pushed for mobile views

**Closed by arekkas** 2015-07-22 18:20 UTC
