### ISSUE TITLE
Add "Share content" for single exercises

### ISSUE THREAD

**Issue by kulla** [serlo-org/athene2#749] opened 2018-09-24 12:58 UTC
While planning the current course at the university we used links to single exercises a lot (we created a link list to exercises to simulate an exercise sheet for a lesson). It would be great to enable the "share content"-button for single exercises to since then it's easier to get the URL to the exercise.

**Comment by inyono** [comment] 2018-09-24 13:35
Duplicate of #746

**Closed by inyono** 2018-09-24 13:35 UTC
