### ISSUE TITLE
Exercise hints

### ISSUE THREAD

**Issue by TinsayeAbye** [serlo-org/athene2#219] opened 2015-09-24 12:26 UTC
are hints even working? If yes then there are some problems 
When i create a new one  i cant see the content
![hint](https://cloud.githubusercontent.com/assets/5862858/10073176/65ca0bcc-62c7-11e5-994a-bb07d2bf093d.PNG)
then i tried to delete it but its stil there, i just can't edit it now 
And the error page has some representation problem
![hint delete edit](https://cloud.githubusercontent.com/assets/5862858/10073244/c7039782-62c7-11e5-904a-a66a7e13d385.PNG)

**Comment by inyono** [comment] 2015-09-24 12:37
Seems like there is some problem with hints, I restored your hint for testing purposes. Should I completely delete the hint until the problem is fixed? Or is it okay that the button is shown although the content does not work?

The problem with deleted hints is a duplicate of #195. The presentation is broken because of a JS error, will have to examine this locally.
````
Uncaught TypeError: Cannot read property 'appendChild' of undefined
```

**Comment by TinsayeAbye** [comment] 2015-09-24 13:02
ok! Well it would be great if you could delete the hint, unless the problem will be solved soon.

**Comment by inyono** [comment] 2015-09-28 14:59
See #222 for broken presentation.

**Closed** 2015-09-29 08:47 UTC
Labels: bug, in progress

**Comment by TinsayeAbye** [comment] 2015-11-02 12:46
is this problem solved? if yes then there is something left...
The hint from above is actually deleted but it appears under the excercise... And when I try to edit it: page is not found

**Comment by inyono** [comment] 2015-11-02 13:00
We still talk about https://de.serlo.org/physik/elektrizitaet-magnetismus/stromkreise-ohmsche-widerstaende/46789 ? Because I can edit the hint.
