### ISSUE TITLE
geogebra layout bug

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#667] opened 2018-04-20 21:10 UTC
test platform: Chromebook

https://de.serlo.org/mathe/geometrie/satzgruppe-pythagoras/satz-pythagoras
![screenshot](https://user-images.githubusercontent.com/3379377/39073958-f9cc70dc-44ef-11e8-881e-06d54f1e4cd9.png)

**Comment by inyono** [comment] 2018-04-21 12:46
Occurs on specific device widths.

**Comment by Knorrke** [comment] 2018-09-12 13:45
duplicate of #135

**Closed by Knorrke** 2018-09-12 13:45 UTC
