### ISSUE TITLE
normalizer: issues with `’`

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#586] opened 2017-09-19 13:43 UTC
If title contains `’`, normalizer fails and maps url to `/`.

**Comment by inyono** [comment] 2017-09-19 13:56
Nvm.... `https://en.serlo.org/85155` redirects to home page?

**Comment by Knorrke** [comment] 2018-04-12 14:11
I can't reproduce this locally. I remember checking this on your laptop @inyono where it was reproducible. Can you check if that's still the case?

**Comment by inyono** [comment] 2018-04-13 09:47
Can't reproduce this anymore.

**Comment by Knorrke** [comment] 2018-04-13 20:28
I'll close this for now and reopen if it happens again.

**Closed by Knorrke** 2018-04-13 20:28 UTC
Labels: bug
