### ISSUE TITLE
Formula rendering is broken on iPad / Safari

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#351] opened 2016-06-06 15:06 UTC
Feedback from a Lab School student
It works with Chrome on iPad

**Comment by arekkas** [comment] 2016-06-08 08:23
@SimonKoehl do we have the possibility to purchase second-hand tablets and smartphones? that way, we could anticipate those problems with testing. I also believe that we need some sort of continuous testing (test all devices every 2 weeks). Do we have capacities to introduce that?

**Comment by inyono** [comment] 2016-06-08 11:33
Formula rendering works on my iPad just fine

**Comment by arekkas** [comment] 2016-09-05 17:03
closing because not reproducible or information missing for reproduction and we have no way to test why it didn't work

**Closed by arekkas** 2016-09-05 17:03 UTC
